Feature/csd 2
CinCoders/cs-deadlines pull request #7
Opened 2023-07-27 19:07 UTC by karensamara

New feature filter by area

2023-07-31 17:05 UTC, dcruzb requested changes

2023-07-31 17:05 UTC, dcruzb commented on src/custom.d.ts
> +declare module '*.svg' {
I believe this is fixed in another branch, this module should not be created.

2023-07-31 17:05 UTC, dcruzb commented on src/pages/Home/index.tsx
> +  width: 20%;
Please avoid using styles in the same file as the code

2023-07-31 18:05 UTC, karensamara commented on src/contexts/CheckedContext.tsx
> +  checked: string[];
The 'checked' state is being used to store the values of the filter by area checkboxes, not as a boolean. To represent the state more accurately, I have renamed it to 'checkedValues'.

2023-08-01 20:53 UTC, dcruzb requested changes

2023-08-01 20:53 UTC, dcruzb commented on src/pages/Home/styles.tsx
> +import styled from 'styled-components';
There is no need to styled-components here

2023-08-01 20:53 UTC, dcruzb commented on package.json
> +    "@types/styled-components": "^5.1.26",
There is no need to use styled-components, could use import { styled } from '@mui/material';

2023-08-01 20:53 UTC, dcruzb commented on src/pages/Home/index.tsx
> +      {loading && <CircularProgress />}
The circular progress need to be inside a div to be centralized

2023-08-01 20:53 UTC, dcruzb commented on src/pages/Home/index.tsx
> +        <FilterContainer>
The style need a revision since this messed with the layout

2023-08-01 20:54 UTC, dcruzb requested changes

2023-08-01 20:54 UTC, dcruzb commented on src/pages/Home/index.tsx
> +    <main>
This defaults to display: block, breaking the flex display from cinnamon

2023-08-01 21:02 UTC, dcruzb approved these changes

2023-08-01 21:02 UTC, merged